server:
  port: 7080

spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
      static-path-pattern: /static/**
  freemarker:
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    cache: false
    expose-spring-macro-helpers: false

    request-context-attribute: request
    settings:
      classic_compatible: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/mes?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: sean
    druid:
      initial-size: 8
      min-idle: 5
      max-active: 10
      query-timeout: 6000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 1800
      filters: stat,config
  redis:
    host: localhost
    port: 6379
    password:

    timeout: 10000
    jedis:
      pool:

        max-idle: 8

        min-idle: 10

        max-active: 100

        max-wait: -1

logging:
  level:
    root: info
    com.wangziyang: debug
    config: classpath:logback.xml
